"""Durable, secret-safe build issue tracking inside the target project."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from .io import append_jsonl, read_json, write_json
from .model import utc_now

_SECRET_ASSIGNMENT = re.compile(
    r"(?i)\b(password|passwd|secret|token|api[_-]?key|access[_-]?key)"
    r"(\s*[=:]\s*)([^\s,;]+)"
)
_AWS_ACCESS_KEY = re.compile(r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b")
_BEARER = re.compile(r"(?i)\bbearer\s+[A-Za-z0-9._~+/=-]+")
_CLASSIFICATIONS = (
    (r"usage limit|quota|rate limit|credits", "quota", False),
    (r"permission|operation not permitted|access denied|eperm", "permission", False),
    (r"no space left|enospc|disk full", "storage", False),
    (r"command not found|executable .*unavailable|missing .*dependency", "dependency", False),
    (r"docker .*not accessible|connection refused|service unavailable", "environment", False),
    (r"test|assert|coverage|approved command failed", "test", True),
    (r"schema|validation|invalid|missing|required output|gate", "validation", True),
    (r"adapter|agent node", "agent", True),
)


def _sanitize(value: str, limit: int = 2000) -> str:
    text = _SECRET_ASSIGNMENT.sub(r"\1\2[REDACTED]", value)
    text = _AWS_ACCESS_KEY.sub("[REDACTED_AWS_ACCESS_KEY]", text)
    text = _BEARER.sub("Bearer [REDACTED]", text)
    return text[:limit]


def _safe_value(value: Any) -> Any:
    if isinstance(value, str):
        return _sanitize(value)
    if isinstance(value, list):
        return [_safe_value(item) for item in value[:50]]
    if isinstance(value, dict):
        return {str(key): _safe_value(item) for key, item in list(value.items())[:50]}
    if isinstance(value, (bool, int, float)) or value is None:
        return value
    return _sanitize(str(value))


def classify_issue(message: str) -> tuple[str, bool]:
    for pattern, classification, retryable in _CLASSIFICATIONS:
        if re.search(pattern, message, re.I):
            return classification, retryable
    return "workflow", True


def _load_issues(project: Path) -> dict[str, Any]:
    value = read_json(project / ".ai" / "issues" / "issues.json", {"version": 1, "issues": []})
    if not isinstance(value, dict) or not isinstance(value.get("issues"), list):
        return {"version": 1, "issues": []}
    return value


def _render_report(project: Path, payload: dict[str, Any]) -> None:
    issues = payload["issues"]
    unresolved = [issue for issue in issues if issue["status"] != "resolved"]
    lines = [
        "# Build issue report",
        "",
        "This report is generated by the workflow failure hook. The append-only event history is",
        "stored in `events.jsonl`; grouped machine-readable issues are in `issues.json`.",
        "",
        f"- Total unique issues: {len(issues)}",
        f"- Unresolved issues: {len(unresolved)}",
        f"- Total error occurrences: {sum(issue['occurrences'] for issue in issues)}",
        "",
        "## Unresolved issues",
        "",
    ]
    if not unresolved:
        lines.append("No unresolved build issues.")
    for issue in unresolved:
        lines.extend(
            [
                f"### {issue['issue_id']} — {issue['classification']}",
                "",
                f"- Status: {issue['status']}",
                f"- Command: `{issue['command']}`",
                f"- Source: `{issue['source']}`",
                f"- Occurrences: {issue['occurrences']}",
                f"- Last seen: {issue['last_seen_at']}",
                f"- Message: {issue['message']}",
                f"- Suggested next step: {issue['next_step']}",
                "",
            ]
        )
    lines.extend(["## Resolved history", ""])
    resolved = [issue for issue in issues if issue["status"] == "resolved"]
    if not resolved:
        lines.append("No recovered issues recorded yet.")
    for issue in resolved:
        lines.append(
            f"- {issue['issue_id']} `{issue['classification']}` — "
            f"{issue['occurrences']} occurrence(s), resolved {issue.get('resolved_at', '')}"
        )
    (project / ".ai" / "issues" / "REPORT.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def _persist(project: Path, payload: dict[str, Any]) -> None:
    root = project / ".ai" / "issues"
    write_json(root / "issues.json", payload)
    issues = payload["issues"]
    unresolved = [issue for issue in issues if issue["status"] != "resolved"]
    summary = {
        "version": 1,
        "updated_at": utc_now(),
        "total_unique": len(issues),
        "total_occurrences": sum(issue["occurrences"] for issue in issues),
        "unresolved": len(unresolved),
        "blocked": sum(issue["status"] == "blocked" for issue in unresolved),
        "resolved": sum(issue["status"] == "resolved" for issue in issues),
        "report": ".ai/issues/REPORT.md",
        "events": ".ai/issues/events.jsonl",
    }
    write_json(root / "summary.json", summary)
    _render_report(project, payload)


def initialize_issue_tracker(project: Path) -> None:
    """Create an empty durable report without overwriting existing issue history."""
    if not (project / ".ai" / "issues" / "issues.json").is_file():
        _persist(project, {"version": 1, "issues": []})


def track_build_issue(
    project: Path,
    *,
    source: str,
    message: str,
    command: str,
    phase: str | None = None,
    node: str | None = None,
    feature: str | None = None,
    attempt: int = 0,
    retryable: bool | None = None,
    context: dict[str, Any] | None = None,
) -> str:
    """Append one error occurrence and update its grouped issue record."""
    safe_message = _sanitize(" ".join(message.split())) or "unspecified workflow error"
    classification, inferred_retryable = classify_issue(safe_message)
    can_retry = inferred_retryable if retryable is None else retryable
    identity = "|".join(
        [source, command, phase or "", node or "", feature or "", safe_message.lower()]
    )
    fingerprint = hashlib.sha256(identity.encode()).hexdigest()
    payload = _load_issues(project)
    issues = payload["issues"]
    issue = next((item for item in issues if item.get("fingerprint") == fingerprint), None)
    now = utc_now()
    if issue is None:
        issue = {
            "issue_id": f"ISSUE-{len(issues) + 1:06d}",
            "fingerprint": fingerprint,
            "classification": classification,
            "status": "open" if can_retry else "blocked",
            "retryable": can_retry,
            "source": source,
            "command": command,
            "phase": phase,
            "node": node,
            "feature": feature,
            "message": safe_message,
            "first_seen_at": now,
            "last_seen_at": now,
            "occurrences": 0,
            "last_attempt": attempt,
            "context": _safe_value(context or {}),
            "next_step": (
                "Correct the recorded cause and resume from the last verified checkpoint."
                if can_retry
                else "Restore the required environment or dependency, then resume the workflow."
            ),
        }
        issues.append(issue)
    issue.update(
        {
            "status": "open" if can_retry else "blocked",
            "retryable": can_retry,
            "last_seen_at": now,
            "occurrences": int(issue.get("occurrences", 0)) + 1,
            "last_attempt": attempt,
            "message": safe_message,
            "context": _safe_value(context or issue.get("context", {})),
            "next_step": (
                "Correct the recorded cause and resume from the last verified checkpoint."
                if can_retry
                else "Restore the required environment or dependency, then resume the workflow."
            ),
        }
    )
    issue.pop("resolved_at", None)
    issue.pop("resolution", None)
    events_path = project / ".ai" / "issues" / "events.jsonl"
    event_count = (
        len(events_path.read_text(encoding="utf-8").splitlines())
        if events_path.is_file()
        else 0
    )
    append_jsonl(
        events_path,
        {
            "event_id": f"ERROR-{event_count + 1:06d}",
            "issue_id": issue["issue_id"],
            "fingerprint": fingerprint,
            "occurred_at": now,
            "source": source,
            "command": command,
            "phase": phase,
            "node": node,
            "feature": feature,
            "attempt": attempt,
            "classification": classification,
            "retryable": can_retry,
            "message": safe_message,
            "context": _safe_value(context or {}),
        },
    )
    _persist(project, payload)
    return fingerprint


def resolve_build_issues(project: Path, fingerprints: list[str], resolution: str) -> None:
    """Mark recovered errors resolved without deleting their event history."""
    if not fingerprints:
        return
    payload = _load_issues(project)
    now = utc_now()
    changed = False
    for issue in payload["issues"]:
        if issue.get("fingerprint") in fingerprints and issue.get("status") != "resolved":
            issue["status"] = "resolved"
            issue["resolved_at"] = now
            issue["resolution"] = _sanitize(resolution)
            changed = True
    if changed:
        _persist(project, payload)


def resolve_matching_build_issues(
    project: Path,
    *,
    commands: set[str],
    sources: set[str] | None = None,
    resolution: str,
) -> None:
    """Resolve prior-run issues after the same controlled boundary later succeeds."""
    payload = _load_issues(project)
    now = utc_now()
    changed = False
    for issue in payload["issues"]:
        if (
            issue.get("status") != "resolved"
            and issue.get("command") in commands
            and (sources is None or issue.get("source") in sources)
        ):
            issue["status"] = "resolved"
            issue["resolved_at"] = now
            issue["resolution"] = _sanitize(resolution)
            changed = True
    if changed:
        _persist(project, payload)


def try_track_build_issue(project: Path, **values: Any) -> str | None:
    """Track an error without replacing the original failure if storage is unavailable."""
    try:
        return track_build_issue(project, **values)
    except Exception:  # noqa: BLE001 - failure recording is secondary to the original failure
        return None


def issue_summary(project: Path) -> dict[str, Any]:
    default = {
        "version": 1,
        "total_unique": 0,
        "total_occurrences": 0,
        "unresolved": 0,
        "blocked": 0,
        "resolved": 0,
        "report": ".ai/issues/REPORT.md",
        "events": ".ai/issues/events.jsonl",
    }
    value = read_json(
        project / ".ai" / "issues" / "summary.json",
        default,
    )
    return value if isinstance(value, dict) else default
